name: Windows Release

on: 
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyInstaller
      run: |
        pyinstaller beavertails/tui.py --add-data "beavertails/static;./beavertails/static" --add-data "beavertails/beavertails.tcss;." --collect-all pulp --onefile --nowindow --noconfirm
        cp dist/tui.exe dist/beavertails_win2019.exe
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/beavertails_win2019.exe"
        allowUpdates: True

